### ISSUE TITLE
Error and lag spike when making a mixture barrel + bedrock players chunks crash when one is in it.

### ISSUE THREAD

**Issue by timtijmen2** [Patbox/brewery#25]
Bedrock players using geyser can not see the chucks with mixture barrels in it at all and java players get a lag spike and a error in their console.
Error in java cleint side console:
```
Negative index in crash report handler (0/12)
22:00:44.474
net.minecraft.class_1255
Render thread
Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException
```

**Comment by timtijmen2** [comment]
Please respond, this is a pretty big issue

**Comment by onebeastchris** [comment]
Once you update Geyser, players should start chunks just fine again; Geyser wasn't ignoring unknown block entity types correctly. The crash however isn't related to that :o
