### ISSUE TITLE
Server crashes after removing bottles from barrel.

### ISSUE THREAD

**Issue by timtijmen2** [Patbox/brewery#38]
The server randomly crashes sometimes when someone removes a bottle from the brewery barrels.

`14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_31420(class_3218.java:407)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18765(class_3218.java:377)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
14.12 13:02:31 [Server] Server thread/INFO [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0, parameter pos
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0(ItemRemoveCallback.kt)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.handler$bcd000$ledger$ledgerCloseScreenLogChanges(class_1703.java:988)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.method_7595(class_1703.java:613)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_14247(class_3222.java:1410)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_7346(class_3222.java:1405)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.SimpleGui.close(SimpleGui.java:225)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.GuiInterface.close(GuiInterface.java:86)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.brewery.block.entity.BrewBarrelSpigotBlockEntity$Gui.onTick(BrewBarrelSpigotBlockEntity.java:318)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:96)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_31420(class_3218.java:407)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18765(class_3218.java:377)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0, parameter pos
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0(ItemRemoveCallback.kt)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.handler$bcd000$ledger$ledgerCloseScreenLogChanges(class_1703.java:988)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.method_7595(class_1703.java:613)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_14247(class_3222.java:1410)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_7346(class_3222.java:1405)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.SimpleGui.close(SimpleGui.java:225)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.GuiInterface.close(GuiInterface.java:86)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.brewery.block.entity.BrewBarrelSpigotBlockEntity$Gui.onTick(BrewBarrelSpigotBlockEntity.java:318)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:96)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_31420(class_3218.java:407)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18765(class_3218.java:377)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0, parameter pos
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0(ItemRemoveCallback.kt)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.handler$bcd000$ledger$ledgerCloseScreenLogChanges(class_1703.java:988)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.method_7595(class_1703.java:613)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_14247(class_3222.java:1410)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_7346(class_3222.java:1405)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.SimpleGui.close(SimpleGui.java:225)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.GuiInterface.close(GuiInterface.java:86)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.brewery.block.entity.BrewBarrelSpigotBlockEntity$Gui.onTick(BrewBarrelSpigotBlockEntity.java:318)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:96)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_31420(class_3218.java:407)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18765(class_3218.java:377)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0, parameter pos
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0(ItemRemoveCallback.kt)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.handler$bcd000$ledger$ledgerCloseScreenLogChanges(class_1703.java:988)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.method_7595(class_1703.java:613)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_14247(class_3222.java:1410)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_7346(class_3222.java:1405)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.SimpleGui.close(SimpleGui.java:225)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.GuiInterface.close(GuiInterface.java:86)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.brewery.block.entity.BrewBarrelSpigotBlockEntity$Gui.onTick(BrewBarrelSpigotBlockEntity.java:318)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:96)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_31420(class_3218.java:407)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18765(class_3218.java:377)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0, parameter pos
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0(ItemRemoveCallback.kt)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.handler$bcd000$ledger$ledgerCloseScreenLogChanges(class_1703.java:988)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.method_7595(class_1703.java:613)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_14247(class_3222.java:1410)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_7346(class_3222.java:1405)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.SimpleGui.close(SimpleGui.java:225)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.GuiInterface.close(GuiInterface.java:86)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.brewery.block.entity.BrewBarrelSpigotBlockEntity$Gui.onTick(BrewBarrelSpigotBlockEntity.java:318)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:96)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_31420(class_3218.java:407)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18765(class_3218.java:377)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0, parameter pos
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0(ItemRemoveCallback.kt)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.handler$bcd000$ledger$ledgerCloseScreenLogChanges(class_1703.java:988)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.method_7595(class_1703.java:613)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_14247(class_3222.java:1410)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_7346(class_3222.java:1405)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.SimpleGui.close(SimpleGui.java:225)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.GuiInterface.close(GuiInterface.java:86)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.brewery.block.entity.BrewBarrelSpigotBlockEntity$Gui.onTick(BrewBarrelSpigotBlockEntity.java:318)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:96)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_31420(class_3218.java:407)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18765(class_3218.java:377)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0, parameter pos
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//com.github.quiltservertools.ledger.callbacks.ItemRemoveCallback$DefaultImpls.EVENT$lambda$1$lambda$0(ItemRemoveCallback.kt)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.handler$bcd000$ledger$ledgerCloseScreenLogChanges(class_1703.java:988)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1703.method_7595(class_1703.java:613)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_14247(class_3222.java:1410)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_7346(class_3222.java:1405)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.SimpleGui.close(SimpleGui.java:225)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.api.gui.GuiInterface.close(GuiInterface.java:86)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.brewery.block.entity.BrewBarrelSpigotBlockEntity$Gui.onTick(BrewBarrelSpigotBlockEntity.java:318)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:96)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3222.method_5773(class_3222.java:697)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_3218.method_18762(class_3218.java:762)
14.12 13:02:32 [Server] Server thread/INFO [STDERR]: 	at knot//net.minecraft.class_1937.method_18472(class_1937.java:502)
14.12 13:02:33 [Multicraft] Skipped 151 lines due to rate limit (160/s)
14.12 13:02:33 [Server] Server thread/INFO Saving chunks for level 'ServerLevel[Seed Test]'/minecraft:the_nether
14.12 13:02:33 [Server] Server thread/INFO Saving chunks for level 'ServerLevel[Seed Test]'/minecraft:the_end
14.12 13:02:33 [Server] Server thread/INFO ThreadedAnvilChunkStorage (world): All chunks are saved
14.12 13:02:33 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
14.12 13:02:33 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
14.12 13:02:33 [Server] Server thread/INFO ThreadedAnvilChunkStorage: All dimensions are saved
14.12 13:02:33 [Server] Server thread/INFO [EasyAuth]: Shutting down EasyAuth.
14.12 13:02:33 [Server] Server thread/INFO [EasyAuth]: Database connection closed successfully
14.12 13:02:33 [Server] Server thread/INFO Successfully drained database queue`

**Comment by Patbox** [comment]
Looks to be issue caused by ledger. Report that to them

**Comment by kanapuro** [comment]
Having the same exact problem.
It's not just Ledger's problem, it could be an incompatibility. Surely there's a fix that can be worked out on this end?
